### ISSUE TITLE
不太懂yolo-nano_person.cfg

### ISSUE THREAD

**Issue by xiaomage11** [lingtengqiu/Yolo_Nano#1]
刚刚看是接触yolo，看到的官方的yolov3.cfg文件都是带有网络层架构的，请问一下，在您的yolo-nano_person.cfg中我只看到了三行信息，不知道yolo-nano的网络架构大神是如何实现的？

**Comment by lingtengqiu** [comment]
具体细节，你可以看model 里头的yolo_nano_helper，我是按照，他的图标实现的



------------------ 原始邮件 ------------------
发件人: xiaomage11 <notifications@github.com&gt;
发送时间: 2020年1月2日 14:56
收件人: lingtengqiu/Yolo_Nano <Yolo_Nano@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[lingtengqiu/Yolo_Nano] 不太懂yolo-nano_person.cfg (#1)

**Comment by xiaomage11** [comment]
好的，感谢，明白了
